### ISSUE TITLE
Version 2.0.1 of the cv.inrange() function failed

### ISSUE THREAD

**Issue by cxr1** [smbape/node-autoit-opencv-com#1]
This is my autohotkey_v2.beta3 code, which works fine in version 1.3 but fails in version 2.0.1 and does not report errors

SetWorkingDir A_ScriptDir

hOpencv := DllCall("LoadLibrary", "str", "opencv_world455.dll", "ptr")
hOpencvCom := DllCall("LoadLibrary", "str", "autoit_opencv_com455.dll", "ptr")
DllCall("autoit_opencv_com455.dll\DllInstall", "int", 1, "wstr", A_IsAdmin = 0 ? "user" : "", "cdecl")

cv := ComObject("OpenCV.cv")
cap := ComObject("OpenCV.cv.VideoCapture")
frame := ComObject("OpenCV.cv.MAT")

cap.open(0)

While True{
    ret := cap.read(frame)
    img_hsv := cv.cvtColor(frame, 40)
    lower_blue := ComArrayMake([110, 50, 50])
    upper_blue := ComArrayMake([130, 255, 255])
    mask := cv.inrange(img_hsv, lower_blue, upper_blue)
    res := cv.bitwise_and(frame, frame, mask := mask)
    cv.imshow("frame", frame)
    cv.imshow("mask", mask)
    cv.imshow("res", res)
}

cv.waitKey()
cv.destroyAllWindows()

ComArrayMake(inputArray)
{
	arr := ComObjArray(VT_VARIANT:=12, inputArray.Length)
	Loop inputArray.Length
	{
		arr[A_Index-1] := inputArray[A_Index]
	}
	return arr
}

**Comment by smbape** [comment]
Hello, thank you for your report.
Are you sure it is inrange the problem not bitwise_and?

There are breaking changes from v1, documented [here](https://github.com/smbape/node-autoit-opencv-com/tree/v2.0.1#breaking-changes-from-v1).

[**bitwise_and**](https://github.com/smbape/node-autoit-opencv-com/blob/v2.0.1/autoit-opencv-com/udf/docs.md#cvbitwise_and) is a function whose signature changes.
mask is now the fourth parameter not the third.

In AutoIt, optional parameters can be replaced with the keyword **Default** or **Null** for Array
I c++, **Default** correspond to `V_VT(in_val) == VT_ERROR && V_ERROR(in_val) == DISP_E_PARAMNOTFOUND`

**Comment by cxr1** [comment]
> Thanks, I put the mask after the fourth parameter and it now works fine。
